Repository chaehoonii/BookHub, pull requests merged in 2022-06, with the labels that each got.

#13 프로필 페이지 중 활동요약, 내 서재 페이지의 프론트엔드 부분의 프로토타입 작성
  BookHub/src/main/java/multi/dokgi/bookhub/profile/controller/ProfileController.java
  BookHub/src/main/resources/static/css/profile/library.css
  BookHub/src/main/resources/static/css/profile/profile.css
  BookHub/src/main/resources/static/css/profile/summary.css
  BookHub/src/main/webapp/WEB-INF/views/profile/library.jsp
  BookHub/src/main/webapp/WEB-INF/views/profile/summary.jsp
Labels: enhancement

#14 top bar 상세페이지 링크 연결
  BookHub/src/main/java/multi/dokgi/bookhub/HomeController.java
  BookHub/src/main/java/multi/dokgi/bookhub/ServletInitializer.java
  BookHub/src/main/resources/static/css/home.css
  BookHub/src/main/resources/static/css/inc/top.css
  BookHub/src/main/resources/static/img/BookHub.jpg
  BookHub/src/main/resources/static/img/BookHub1.png
  BookHub/src/main/resources/static/img/fav_logo.jpg
  BookHub/src/main/webapp/WEB-INF/views/inc/bottom.jspf
  BookHub/src/main/webapp/WEB-INF/views/inc/top.jspf
  BookHub/src/main/webapp/WEB-INF/views/main.jsp
Labels: documentation

#18 메인페이지에서 로그인가능, SNS회원가입로직, top.css폰트, ServletInitializer수정
  BookHub/src/main/java/multi/dokgi/bookhub/BookHubApplication.java
  BookHub/src/main/java/multi/dokgi/bookhub/HomeController.java
  BookHub/src/main/java/multi/dokgi/bookhub/ServletInitializer.java
  BookHub/src/main/java/multi/dokgi/bookhub/config/auth/SecurityConfig.java
  BookHub/src/main/java/multi/dokgi/bookhub/user/controller/UserController.java
  BookHub/src/main/resources/static/css/inc/top.css
  BookHub/src/main/resources/static/css/user/common_style.css
  BookHub/src/main/resources/static/css/user/user_register_new.css
  BookHub/src/main/resources/static/js/user/user_register.js
  BookHub/src/main/webapp/WEB-INF/views/err/401.jsp
  BookHub/src/main/webapp/WEB-INF/views/err/403.jsp
  BookHub/src/main/webapp/WEB-INF/views/err/404.jsp
  BookHub/src/main/webapp/WEB-INF/views/err/500.jsp
  BookHub/src/main/webapp/WEB-INF/views/err/libs/libsScript.jsp
  BookHub/src/main/webapp/WEB-INF/views/err/libs/libsStyles.jsp
  BookHub/src/main/webapp/WEB-INF/views/inc/top.jspf
  BookHub/src/main/webapp/WEB-INF/views/index.jsp
  BookHub/src/main/webapp/WEB-INF/views/register.jsp
Labels: enhancement

#17 활동 요약 페이지에 최대 6건의 독서 활동이 표시되도록 구현
  BookHub/src/main/java/multi/dokgi/bookhub/profile/controller/ProfileController.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/controller/ReadingLogController.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/dao/IReadingLogDAO.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/dto/ReadingLogDTO.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/service/IReadingLogService.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/service/ReadingLogServiceImpl.java
  BookHub/src/main/resources/mybatis/mappers/readinglog-mapper.xml
  BookHub/src/main/resources/static/css/profile/profile.css
  BookHub/src/main/resources/static/css/profile/summary.css
  BookHub/src/main/resources/static/css/readinglog/edit.css
  BookHub/src/main/resources/static/css/readinglog/readinglog.css
  BookHub/src/main/webapp/WEB-INF/views/profile/library.jsp
  BookHub/src/main/webapp/WEB-INF/views/profile/summary.jsp
  BookHub/src/main/webapp/WEB-INF/views/readinglog/edit.jsp
Labels: enhancement

#19 CSS 참조 시의 경로를 상대경로 → 절대경로로 변경
  BookHub/src/main/webapp/WEB-INF/views/inc/bottom.jspf
  BookHub/src/main/webapp/WEB-INF/views/inc/top.jspf
Labels: bug

#20 활동 기록 표시 기능 보완
  BookHub/src/main/java/multi/dokgi/bookhub/profile/controller/ProfileController.java
  BookHub/src/main/resources/mybatis/mappers/readinglog-mapper.xml
  BookHub/src/main/webapp/WEB-INF/views/profile/summary.jsp
Labels: bug

#21 캘린더 접근 권한 수정 및 활동 요약 페이지 수정
  BookHub/src/main/java/multi/dokgi/bookhub/profile/controller/ProfileController.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/controller/ReadingLogController.java
  BookHub/src/main/resources/mybatis/mappers/readinglog-mapper.xml
  BookHub/src/main/resources/static/css/inc/top.css
  BookHub/src/main/resources/static/css/profile/summary.css
  BookHub/src/main/webapp/WEB-INF/views/profile/library.jsp
  BookHub/src/main/webapp/WEB-INF/views/profile/summary.jsp
  BookHub/src/main/webapp/WEB-INF/views/readinglog/edit.jsp
Labels: enhancement

#22 [FEAT] profile → readinglog로 명칭 변경 및 경로 수정
  BookHub/src/main/java/multi/dokgi/bookhub/profile/controller/ProfileController.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/controller/ReadingLogController.java
  BookHub/src/main/resources/static/css/profile/profile.css
  BookHub/src/main/resources/static/css/readinglog/edit.css
  BookHub/src/main/resources/static/css/readinglog/library.css
  BookHub/src/main/resources/static/css/readinglog/readinglog.css
  BookHub/src/main/resources/static/css/readinglog/summary.css
  BookHub/src/main/webapp/WEB-INF/views/inc/top.jspf
  BookHub/src/main/webapp/WEB-INF/views/readinglog/edit.jsp
  BookHub/src/main/webapp/WEB-INF/views/readinglog/library.jsp
  BookHub/src/main/webapp/WEB-INF/views/readinglog/summary.jsp
Labels: enhancement

#23 readinglog→ rlog로 명칭 변경 및 경로 수정
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/controller/ReadingLogController.java
  BookHub/src/main/resources/static/css/rlog/edit.css
  BookHub/src/main/resources/static/css/rlog/library.css
  BookHub/src/main/resources/static/css/rlog/rlog.css
  BookHub/src/main/resources/static/css/rlog/summary.css
  BookHub/src/main/webapp/WEB-INF/views/inc/top.jspf
  BookHub/src/main/webapp/WEB-INF/views/rlog/edit.jsp
  BookHub/src/main/webapp/WEB-INF/views/rlog/library.jsp
  BookHub/src/main/webapp/WEB-INF/views/rlog/summary.jsp
Labels: enhancement

#24 최근 독서 활동, 최근 읽은 책 기능 구현 및 보완
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/controller/ReadingLogController.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/dao/IReadingLogDAO.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/dto/ReadingCalendarDTO.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/dto/ReadingLogDTO.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/service/IReadingLogService.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/service/ReadingLogServiceImpl.java
  BookHub/src/main/resources/mybatis/mappers/readinglog-mapper.xml
  BookHub/src/main/resources/static/css/rlog/rlog.css
  BookHub/src/main/resources/static/css/rlog/summary.css
  BookHub/src/main/resources/static/js/rlog/summary.js
  BookHub/src/main/webapp/WEB-INF/views/rlog/edit.jsp
  BookHub/src/main/webapp/WEB-INF/views/rlog/library.jsp
  BookHub/src/main/webapp/WEB-INF/views/rlog/summary.jsp
Labels: enhancement

#25 회원정보수정 v1.0
  BookHub/src/main/java/multi/dokgi/bookhub/HomeController.java
  BookHub/src/main/java/multi/dokgi/bookhub/user/controller/UserController.java
  BookHub/src/main/java/multi/dokgi/bookhub/user/service/IUserService.java
  BookHub/src/main/java/multi/dokgi/bookhub/user/service/UserServiceImpl.java
  BookHub/src/main/resources/static/css/user/common_style.css
  BookHub/src/main/resources/static/css/user/settings-asidebar.css
  BookHub/src/main/resources/static/css/user/settings-deleteuser.css
  BookHub/src/main/resources/static/css/user/settings-modifyuser.css
  BookHub/src/main/webapp/WEB-INF/views/err/libs/libsScript.jsp
  BookHub/src/main/webapp/WEB-INF/views/err/libs/libsStyles.jsp
  BookHub/src/main/webapp/WEB-INF/views/inc/bottom.jspf
  BookHub/src/main/webapp/WEB-INF/views/inc/top.jspf
  BookHub/src/main/webapp/WEB-INF/views/readinglog/summary.jsp
  BookHub/src/main/webapp/WEB-INF/views/user/register.jsp
  BookHub/src/main/webapp/WEB-INF/views/user/settings-deleteuser.jsp
  BookHub/src/main/webapp/WEB-INF/views/user/settings-modifyuser.jsp
  bookhub.sql
Labels: enhancement

#26 Feat/home chaehoon
  BookHub/src/main/resources/static/css/home.css
  BookHub/src/main/resources/static/css/inc/top.css
  BookHub/src/main/webapp/WEB-INF/views/inc/bottom.jspf
  BookHub/src/main/webapp/WEB-INF/views/inc/top.jspf
  BookHub/src/main/webapp/WEB-INF/views/main.jsp
Labels: enhancement

#27 회원가입 로직개선, 회원정보수정 및 탈퇴 구현
  BookHub/src/main/java/multi/dokgi/bookhub/config/auth/SecurityConfig.java
  BookHub/src/main/java/multi/dokgi/bookhub/user/controller/UserController.java
  BookHub/src/main/java/multi/dokgi/bookhub/user/dao/IUserDAO.java
  BookHub/src/main/java/multi/dokgi/bookhub/user/service/IUserService.java
  BookHub/src/main/java/multi/dokgi/bookhub/user/service/UserServiceImpl.java
  BookHub/src/main/resources/mybatis/mappers/user-mapper.xml
  BookHub/src/main/resources/static/css/user/common_style.css
  BookHub/src/main/resources/static/css/user/settings-asidebar.css
  BookHub/src/main/resources/static/css/user/settings-modifyuser.css
  BookHub/src/main/resources/static/css/user/settings-withdraw.css
  BookHub/src/main/resources/static/css/user/user_register_new.css
  BookHub/src/main/resources/static/js/user/settings-modifyuser.js
  BookHub/src/main/resources/static/js/user/settings-withdraw.js
  BookHub/src/main/resources/static/js/user/user_register.js
  BookHub/src/main/webapp/WEB-INF/views/inc/top.jspf
  BookHub/src/main/webapp/WEB-INF/views/user/register.jsp
  BookHub/src/main/webapp/WEB-INF/views/user/settings-modifyuser.jsp
  BookHub/src/main/webapp/WEB-INF/views/user/settings-withdraw.jsp
Labels: enhancement

#30 booklist 구현 완료
  BookHub/src/main/java/multi/dokgi/bookhub/booklist/BookListController.java
  BookHub/src/main/java/multi/dokgi/bookhub/booklist/ReviewService.java
  BookHub/src/main/java/multi/dokgi/bookhub/booklist/ReviewServiceImpl.java
  BookHub/src/main/java/multi/dokgi/bookhub/booklist/dao/ReviewDAO.java
  BookHub/src/main/resources/mybatis/mappers/review-mapper.xml
  BookHub/src/main/resources/static/css/booklist/bookdetail.css
  BookHub/src/main/resources/static/css/booklist/booklist.css
  BookHub/src/main/resources/static/css/booklist/booksearch.css
  BookHub/src/main/resources/static/js/booklist/bookdetail.js
  BookHub/src/main/webapp/WEB-INF/views/booklist/bookdetail.jsp
  BookHub/src/main/webapp/WEB-INF/views/booklist/booksearch.jsp
Labels: enhancement

#31 top.jspf에서 bootstrap.css와 겹치는 부분 조정, 검색기능 구현 #1
  BookHub/src/main/resources/static/css/inc/top.css
  BookHub/src/main/resources/static/js/mainsearch.js
  BookHub/src/main/webapp/WEB-INF/views/inc/top.jspf
Labels: enhancement

#32 데이터베이스 구조 변경에 따른 수정
  BookHub/src/main/java/multi/dokgi/bookhub/booklist/controller/BookListController.java
  BookHub/src/main/java/multi/dokgi/bookhub/booklist/dao/ICategoryDAO.java
  BookHub/src/main/java/multi/dokgi/bookhub/booklist/dao/IReviewDAO.java
  BookHub/src/main/java/multi/dokgi/bookhub/booklist/service/BookListServiceImpl.java
  BookHub/src/main/java/multi/dokgi/bookhub/booklist/service/IBookListService.java
  BookHub/src/main/java/multi/dokgi/bookhub/booklist/service/IReviewService.java
  BookHub/src/main/java/multi/dokgi/bookhub/booklist/service/ReviewServiceImpl.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/controller/ReadingLogController.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/dto/ReadingLogDTO.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/service/IReadingLogService.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/service/ReadingLogServiceImpl.java
  BookHub/src/main/resources/mybatis/mappers/booklist-mapper.xml
  BookHub/src/main/resources/mybatis/mappers/readinglog-mapper.xml
  BookHub/src/main/resources/mybatis/mappers/review-mapper.xml
  BookHub/src/main/webapp/WEB-INF/views/rlog/library.jsp
  BookHub/src/main/webapp/WEB-INF/views/rlog/summary.jsp
Labels: enhancement

#34 Bootstrap 제거 추가 작업 및 공통 폰트 적용
  BookHub/pom.xml
  BookHub/src/main/resources/static/css/booklist/bookdetail.css
  BookHub/src/main/resources/static/css/booklist/booklist.css
  BookHub/src/main/resources/static/css/home.css
  BookHub/src/main/resources/static/css/inc/top.css
  BookHub/src/main/resources/static/css/rlog/library.css
  BookHub/src/main/resources/static/css/rlog/summary.css
  BookHub/src/main/webapp/WEB-INF/views/rlog/library.jsp
  BookHub/src/main/webapp/WEB-INF/views/rlog/summary.jsp
Labels: enhancement

#35 booklist css 수정
  BookHub/src/main/resources/static/css/booklist/bookdetail.css
  BookHub/src/main/resources/static/css/booklist/booklist.css
Labels: enhancement

#36 bottom css 완료 및 top 검색창 간격 조정 #1
  BookHub/src/main/java/multi/dokgi/bookhub/IntroController.java
  BookHub/src/main/resources/static/css/inc/bottom.css
  BookHub/src/main/resources/static/css/inc/top.css
  BookHub/src/main/webapp/WEB-INF/views/inc/bottom.jspf
  BookHub/src/main/webapp/WEB-INF/views/inc/top.jspf
  BookHub/src/main/webapp/WEB-INF/views/introduction.jsp
  BookHub/src/main/webapp/WEB-INF/views/main.jsp
Labels: enhancement

#38 메인에서 bottom 나오는 버그 수정 #1
  BookHub/src/main/resources/static/css/home.css
Labels: bug, enhancement

#39 bottom 수정 #1
  BookHub/src/main/resources/static/css/home.css
  BookHub/src/main/resources/static/css/inc/bottom.css
Labels: bug

#40 bottom 메인에 보이는 문제 최종 #1
  BookHub/src/main/resources/static/css/home.css
  BookHub/src/main/resources/static/css/inc/bottom.css
  BookHub/src/main/resources/static/css/inc/top.css
Labels: bug

#41 파비콘 업데이트 #1
  BookHub/src/main/resources/static/img/fav_logo.jpg
  BookHub/src/main/resources/static/img/fav_logo.png
  BookHub/src/main/webapp/WEB-INF/views/inc/top.jspf
Labels: enhancement

#42 Settings페이지 스타일, UN_USER권한 페이지이동 차단
  BookHub/pom.xml
  BookHub/src/main/java/multi/dokgi/bookhub/config/auth/SecurityConfig.java
  BookHub/src/main/resources/static/css/user/common_style.css
  BookHub/src/main/webapp/WEB-INF/views/user/register.jsp
  BookHub/src/main/webapp/WEB-INF/views/user/settings-modifyuser.jsp
  BookHub/src/main/webapp/WEB-INF/views/user/settings-withdraw.jsp
Labels: enhancement

#44 booklist 백엔드 진행도 계산 수정 #5
  BookHub/src/main/java/multi/dokgi/bookhub/booklist/service/ReviewServiceImpl.java
Labels: enhancement

#47 소개 페이지 제작 #46
  BookHub/src/main/resources/static/css/intro.css
  BookHub/src/main/resources/static/css/main.css
  BookHub/src/main/resources/static/img/intro/bookregister.png
  BookHub/src/main/resources/static/js/booklist/bookdetail.js
  BookHub/src/main/webapp/WEB-INF/views/introduction.jsp
  BookHub/src/main/webapp/WEB-INF/views/main.jsp
Labels: enhancement

#48 독서활동 기록 페이지 구현
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/controller/ReadingLogController.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/dao/IReadingLogDAO.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/dto/ReadingReviewDTO.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/service/IReadingLogService.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/service/ReadingLogServiceImpl.java
  BookHub/src/main/resources/mybatis/mappers/readinglog-mapper.xml
  BookHub/src/main/resources/static/css/booklist/bookdetail.css
  BookHub/src/main/resources/static/css/booklist/booklist.css
  BookHub/src/main/resources/static/css/inc/bottom.css
  BookHub/src/main/resources/static/css/inc/top.css
  BookHub/src/main/resources/static/css/rlog/book.css
  BookHub/src/main/resources/static/css/rlog/edit.css
  BookHub/src/main/resources/static/css/rlog/library.css
  BookHub/src/main/resources/static/css/rlog/rlog.css
  BookHub/src/main/resources/static/css/rlog/summary.css
  BookHub/src/main/resources/static/css/user/common_style.css
  BookHub/src/main/resources/static/js/booklist/bookdetail.js
  BookHub/src/main/resources/static/js/rlog/book.js
  BookHub/src/main/resources/static/js/rlog/library.js
  BookHub/src/main/resources/static/js/rlog/summary.js
  BookHub/src/main/webapp/WEB-INF/views/booklist/bookdetail.jsp
  BookHub/src/main/webapp/WEB-INF/views/inc/bottom.jspf
  BookHub/src/main/webapp/WEB-INF/views/inc/top.jspf
  BookHub/src/main/webapp/WEB-INF/views/rlog/book.jsp
  BookHub/src/main/webapp/WEB-INF/views/rlog/edit.jsp
  BookHub/src/main/webapp/WEB-INF/views/rlog/library.jsp
  BookHub/src/main/webapp/WEB-INF/views/rlog/summary.jsp
Labels: enhancement

#49 독서기록 작성 기능 구현
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/controller/ReadingLogController.java
  BookHub/src/main/resources/static/css/rlog/book.css
  BookHub/src/main/resources/static/css/rlog/library.css
  BookHub/src/main/webapp/WEB-INF/views/rlog/book.jsp
Labels: enhancement

#50 독서활동 기록 기능 추가 구현 및 다른 사용자의 기록이 보이는 오류 수정
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/dao/IReadingLogDAO.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/dto/ReadingLogDTO.java
  BookHub/src/main/java/multi/dokgi/bookhub/readinglog/service/ReadingLogServiceImpl.java
  BookHub/src/main/resources/mybatis/mappers/readinglog-mapper.xml
  BookHub/src/main/resources/static/css/rlog/book.css
  BookHub/src/main/resources/static/js/rlog/book.js
  BookHub/src/main/webapp/WEB-INF/views/rlog/book.jsp
Labels: enhancement
